import { useEffect, useRef } from "react";

export default function FAQs() {
    const sections = useRef([]);

    useEffect(() => {
        const observer = new IntersectionObserver(
            (entries) => {
                entries.forEach((entry) => {
                    if (entry.isIntersecting && !entry.target.classList.contains("animate-fadeInUp")) {
                        entry.target.classList.add("animate-fadeInUp");
                        observer.unobserve(entry.target);
                    }
                });
            },
            { threshold: 0.2 }
        );

        sections.current.forEach((section) => {
            if (section) observer.observe(section);
        });

        return () => {
            sections.current.forEach((section) => {
                if (section) observer.unobserve(section);
            });
        };
    }, []);

    const FAQs = [
        {
            question: "How can I be sure that the data I see here is real and recently updated?",
            answer: "The data collected on our website are marked with data source and the time range is indicated.",
        },
        {
            question: "Are the reviews I see on the cover page real? Does this mean that the reviews I leave are also at risk of being exposed?",
            answer: "The comments you see on the cover page are not real, they are generated by AI, and there is no risk of your comments being exposed.",
        },
        {
            question: "What is the use of registering an account?",
            answer: "You can subscribe to the vaccines you are interested in with an account. When there is any update on the vaccine information, we will automatically notify you.",
        },
        {
            question: "Did you conduct the surveys on the Survey page?",
            answer: "No. The results come from other survey agencies, and the data source is also noted.",
        },
        {
            question: "Do you have an inclination towards vaccines? Support or ...?",
            answer: "Our value orientation is to convey correct information to the public as much as possible, without inciting or slandering. We hope that everyone can make their own choices with free subjective will in the face of objective information.",
        },
    ];

    return (
        <div ref={(el) => sections.current[0] = el}
        className="flex flex-col md:flex-row gap-8 p-6 mt-20 opacity-0 translate-y-10 transition-all duration-700">
            {/* Left Column */}
            <div className="flex-1 md:flex-[1] items-center text-[#152063]">
                <div className="flex flex-row gap-4 items-center mb-4">
                    <img src="/image/question-icon.png" alt="question-icon" />
                <p className="text-[40px] font-bold">FAQs</p>
                </div>
                <p className="text-[20px]">All the questions you want to ask...</p>
            </div>

            {/* Right Column */}
            <div className="flex-1 md:flex-[2] space-y-6">
                {FAQs.map((faq, index) => (
                    <div key={index} className="border-b border-gray-400 pb-4">
                        <h3 className="text-lg font-semibold mb-2">{faq.question}</h3>
                        <p className="text-gray-500">{faq.answer}</p>
                    </div>
                ))}
            </div>
        </div>
    );
}
