server:
  port: 8060

spring:
  profiles:
    active: dev # 切换环境配置
  application:
    name: vaccine-safety-confidence
  mybatis-plus:
    configuration:
      # MyBatis 配置
      map-underscore-to-camel-case: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB



#  国际化（i18n）消息资源文件配置
#  messages:
#    basename: i18n/messages # 消息资源文件位于 classpath:/i18n/ 目录下，文件名的前缀是 messages。