server:
  port: 8050
  url: http://127.0.0.1

spring:
  application:
    name: movie-review-system
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
#  mybatis-plus:
#    configuration:
#      # MyBatis 配置
#      map-underscore-to-camel-case: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.138.179.126:3306/miles_vax_confidence?createDatabaseIfNotExist=true
    username: root
    password: 90Miles2024
#  sql:
#    init:
#      schema-locations: classpath:sql/schema.sql
#      mode: always

swagger:
  enabled: true
